### ISSUE TITLE
Extensions search bar - hard to see what text has been selected or highlighted

### ISSUE THREAD

**Issue by nmoore93** [ZYinMD/sepia#2]
Hi, First of all thanks for making and sharing this great theme! One very, very small issue I have seen while using the Sepia theme is highlighting text within the Extensions search bar does not show the highlight itself.

To reproduce:

1. Navigate to Extensions
2. Enter some text within the `Search Extensions in Marketplace` search box
3. Select all text entered (Double click the entered text or press cntrl-a  or click and drag cursor over text)
4. Text should be highlighted but it is hard to see what has been highlighted

Example, this image should have the text highlighted / slected:
![highlightedExtensionSearchText](https://user-images.githubusercontent.com/22432163/57985463-53081b00-7a60-11e9-9ff7-3479a8fbd422.png)

Thanks!

**Comment by ZYinMD** [comment]
Thanks very much for the find! I pushed up a fix, and you should see the change soon, if not already. 

It's not a perfect fix, the color in this search box is still more transparent than other search boxes, but it's at least visible now. Apparently it's a [known issue](https://github.com/microsoft/vscode/issues/75012) of VSCode.

**Comment by nmoore93** [comment]
Thanks very much for the quick fix! I wasn't aware of the know VSCode issue, but it is definitely visible now. Thanks again for the great theme and quick fix! I will close this issue now.

**Comment by ZYinMD** [comment]
You're welcome. 

Since you seem to like the theme, you might as well [give a rating](https://marketplace.visualstudio.com/items?itemName=ZYinMD.Sepia), although I don't think the ratings matter in any practical ways at all ~
